AppGoodFriendsMvc/Controllers/DetailsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppGoodFriendsMvc.Models;
using Models.DTO;
using Services;
using static AppGoodFriendsMvc.Models.EditFriendModel;
using AppGoodFriendsMvc.SeidoHelpers;
namespace AppGoodFriendsMvc.Controllers;

public class DetailsController : Controller
{
    private readonly ILogger<DetailsController> _logger;
    private readonly IFriendsService _service;

    public DetailsController(ILogger<DetailsController> logger, IFriendsService service)
    {
        _logger = logger;
        _service = service;
    }
    #region View details
    [HttpGet]
    public async Task<IActionResult> ViewFriend(string id)
    {
        var vwm = new ViewFriendModel();
        Guid _friendId = Guid.Parse(id);
        vwm.Friend = await _service.ReadFriendAsync(_friendId, false);
        vwm.FriendId = _friendId;

        return View("ViewFriend", vwm);
    }
    [HttpPost]
    public async Task<IActionResult> DeletePet(ViewFriendModel vwm, Guid itemId)
    {
        await _service.DeletePetAsync(itemId);
        vwm.Friend = await _service.ReadFriendAsync(vwm.FriendId, false);

        return View("ViewFriend", vwm);
    }
    public async Task<IActionResult> DeleteQuote(ViewFriendModel vwm, Guid itemId)
    {
        vwm.Friend = await _service.ReadFriendAsync(vwm.FriendId, false);
        vwm.Friend.Quotes = vwm.Friend.Quotes.Where(x => x.QuoteId != itemId).ToList();
        await _service.UpdateFriendAsync(new FriendCUdto(vwm.Friend));
        vwm.Friend = await _service.ReadFriendAsync(vwm.FriendId, false);

        return View("ViewFriend", vwm);
    }

    #endregion

    #region Edit details

    [HttpGet]
    public async Task<IActionResult> EditFriend()
    {
        var vwm = new EditFriendModel();
        if (Guid.TryParse(Request.Query["id"], out Guid _groupId))
        {
            //Read a music group from 
            var mg = await _service.ReadFriendAsync(_groupId, false);

            //Populate the InputModel from the music group
            vwm.FriendInput = new FriendIM(mg);
            vwm.PageHeader = "Edit details of a friend";

        }
        else
        {
            //Create an empty music group
            vwm.FriendInput = new FriendIM();
            vwm.FriendInput.StatusIM = StatusIM.Inserted;
            vwm.FriendInput.FirstName = null;
            vwm.FriendInput.LastName = null;
            vwm.FriendInput.Email = null;
            vwm.FriendInput.Birthday = null;
            vwm.FriendInput.Address = new AddressIM();
            vwm.FriendInput.Address.StatusIM = StatusIM.Inserted;

            vwm.PageHeader = "Create a new a friend";
        }

        return View("EditFriend", vwm);
    }
    [HttpPost]
    public async Task<IActionResult> Save(EditFriendModel vwm)
    {
        string[] keys = { "FriendInput.FirstName",
                            "FriendInput.LastName",
                            "FriendInput.Address.ZipCode",
                            "FriendInput.Address.StreetAddress",
                            "FriendInput.Address.City",
                            "FriendInput.Address.Country",};

        if (!ModelState.IsValidPartially(out ModelValidationResult validationResult, keys))
        {
            vwm.ValidationResult = validationResult;
            return View("EditFriend", vwm);
        }

        //This is where the music plays
        //First, are we creating a new Music group or editing another
        if (vwm.FriendInput.StatusIM == StatusIM.Inserted)
        {
            var newMg = await _service.CreateFriendAsync(vwm.FriendInput.CreateCUdto());
            //get the newly created FriendId
            vwm.FriendInput.FriendId = newMg.FriendId;
        }

        // Do update address
        var mg = await vwm.SaveAddress(_service);

        // Update the Friend itself
        mg = vwm.FriendInput.UpdateModel(mg);
        await _service.UpdateFriendAsync(new FriendCUdto(mg));

        if (vwm.FriendInput.StatusIM == StatusIM.Inserted)
        {
            return RedirectToAction("ListOfFriends", "Overview");
        }

        return Redirect($"ViewFriend?id={vwm.FriendInput.FriendId}");
    }
    

    #endregion

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AppGoodFriendsMvc/Controllers/OverviewController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppGoodFriendsMvc.Models;
using Services;

namespace AppGoodFriendsMvc.Controllers;

public class OverviewController : Controller
{
    private readonly ILogger<OverviewController> _logger;
    private readonly IFriendsService _service;

    public OverviewController(ILogger<OverviewController> logger, IFriendsService service)
    {
        _logger = logger;
        _service = service;
    }

    #region Countries
    [HttpGet]
    public async Task<IActionResult> OverviewCountry()
    {
        var vwm = new OverviewCountryModel();

        //get db info overview
        vwm._info = await _service.InfoAsync();

        //get GstUsrInfoFriendsDto
        vwm.Friends = vwm._info.Friends;

        //grouping by country turning GstUsrInfoFriendsDto into GroupedFriendsDTO
        vwm.GroupedFriends = vwm.Friends.GroupBy(f => f.Country)
                                .Select(c => new GroupedFriendsDTO
                                {
                                    Country = c.Key,
                                    NrFriends = c.Where(f => f.City == null).Sum(f => f.NrFriends),
                                    NrCities = c.Where(f => f.City != null).Select(f => f.City)
                                                .Count() // counting number of cities in the country not including null values
                                })
                                .ToList();

        return View(vwm);
    }
    #endregion

    #region Cities

    [HttpGet]
    [Route("Overview/OverViewCities")]
    public async Task<IActionResult> OnGet(string country)
    {
        var vwm = new OverviewCitiesModel();
        //fetching country from query string
        vwm.Country = Request.Query["country"].ToString();

        //fetching db info from service
        vwm._info = await _service.InfoAsync();

        //if country is known find cities with linq
        //group the friends list by city and sum the friends 
        vwm.Friends = vwm._info.Friends.Where(f => f.Country == vwm.Country)
                                .GroupBy(c => c.City)
                                .Select(c => new CitySummaryDTO // extracting whats needed from the GstUsrInfoFriendsDto and putting it into the summary
                                {
                                    City = c.Key, // city taken from the Groupby key
                                    NrFriends = c.Sum(f => f.NrFriends), // summing number of friends in this city
                                    NrPets = 0 // 0 because it's friends list not pets
                                })
                                .ToList();


        vwm.Pets = vwm._info.Pets.Where(f => f.Country == vwm.Country && f.Country != null)
                                .GroupBy(c => c.City)
                                .Select(c => new CitySummaryDTO 
                                {
                                    City = c.Key,
                                    NrFriends = 0, 
                                    NrPets = c.Sum(p => p.NrPets)
                                })
                                .ToList();

        /* before the above 2 Linq statements _info.Friends and Pets were 2 different data types 
            now they are lists of CitySummaryDTO and can be combined into one list
        */ 
        
        vwm.FriendPetSummaries = vwm.Pets.Concat(vwm.Friends)
                            .GroupBy(c => c.City)
                            .Select(c => new CitySummaryDTO // combining number of friends and pets living in the same city 
                            {
                                City = c.Key,
                                NrPets = c.Sum(p => p.NrPets),
                                NrFriends = c.Sum(f => f.NrFriends)
                            })
                            .ToList();
    


        return View("OverviewCities", vwm);
    }

    #endregion


    #region List of friends
    [HttpGet]
    public async Task<IActionResult> ListOfFriends(string search, int pagenr)
    {
        var vwm = new ListOfFriendsModel(){ ThisPageNr = pagenr, SearchFilter = search };

        //Use the Service
        var resp = await _service.ReadFriendsAsync(vwm.UseSeeds, false, vwm.SearchFilter, vwm.ThisPageNr, vwm.PageSize);
        vwm.Friends = resp.PageItems;
        vwm.NrOfFriends = resp.DbItemsCount;

        //Pagination
        vwm.UpdatePagination(resp.DbItemsCount);
        

        return View("ListOfFriends", vwm);
    }

    [HttpPost]
    public async Task<IActionResult> Search(ListOfFriendsModel vwm)
    {
        //Use the Service
        var resp = await _service.ReadFriendsAsync(vwm.UseSeeds, false, vwm.SearchFilter, vwm.ThisPageNr, vwm.PageSize);
        vwm.Friends = resp.PageItems;
        vwm.NrOfFriends = resp.DbItemsCount;

        //Pagination
        vwm.UpdatePagination(resp.DbItemsCount);

        //Page is rendered as the postback is part of the form tag
        return View("ListOfFriends", vwm);
    }
    [HttpPost]
    public async Task<IActionResult> DeleteFriend(Guid itemId, ListOfFriendsModel vwm)
    {
        await _service.DeleteFriendAsync(itemId);

        //Use the Service
        var resp = await _service.ReadFriendsAsync(vwm.UseSeeds, false, vwm.SearchFilter, vwm.ThisPageNr, vwm.PageSize);
        vwm.Friends = resp.PageItems;
        vwm.NrOfFriends = resp.DbItemsCount;

        //Pagination
        vwm.UpdatePagination(resp.DbItemsCount);

        return View("ListOfFriends", vwm);
    }

    #endregion

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AppGoodFriendsMvc/Views/Overview/ListOfFriends.cshtml
@model ListOfFriendsModel
@using Microsoft.AspNetCore.Authorization;
@using Microsoft.AspNetCore.Identity;

@{
    ViewData["Title"] = "List of friends";

}


      
  <!-- Page list-of-friends -->
  <div class="container px-4 py-4" id="list-of-friends">
  <h2 class="pb-2 border-bottom">List of friends</h2>

    <p>There are @Model.NrOfFriends friends 
        @if(Model.SearchFilter is not null)
        {
          <span>matching the search criteria @Model.SearchFilter</span>
        }
    </p>
    <form method="post" class="needs-validation" method="post" novalidate>
      <label class="form-check-label" for="useSeeds">Use seeded data</label>
      <input asp-for="UseSeeds" class="form-check-input" type="checkbox" id="useSeeds">
            <div class="row mb-2 text-center">
                  <!-- Search filter-->
                  <div class="row mb-2 text-center">
                      <div class="col-md-6 ">
                          <input asp-for="SearchFilter" class="form-control" type="search" placeholder="Search" aria-label="Search">
                      </div>
                      <div class="col-md-2 ">
                          <button asp-controller="Overview" asp-action="Search" class="btn btn-outline-success" type="submit">Search</button>
                      </div>
                  </div>
            </div>

            <div class="row mb-2 text-center">
              <input type="hidden" name="itemId" data-seido-selected-item-id-target />
              <div class="col-md-4 themed-grid-col">Name</div>
              <div class="col-md-4 themed-grid-col">Address</div>
              <div class="col-md-2 themed-grid-col">Info</div>
              <div class="col-md-2 themed-grid-col">
                  <a href="@(Url.Action("EditFriend", "Details"))" class="btn btn-success btn-sm" type="button">Add</a>
              </div>
            </div>
            <div class="row mb-2 text-center">

                @if(Model.Friends is not null)
                {
                    @foreach(var item in Model.Friends)
                    {
                        <div class="col-md-4 themed-grid-col">
                          @item.FirstName @item.LastName
                          <div class="col-md-16">@item.Email</div>
                        </div>
                        <div class="col-md-4 themed-grid-col">
                          @(item.Address?.StreetAddress ?? "No address" )
                          <div class="col-md-16">@item.Address?.ZipCode @item.Address?.City</div>
                          <div class="col-md-16">@item.Address?.Country</div>
                        </div>
                        <div class="col-md-2 themed-grid-col">
                          <div class="col-md-16">Born: @(item.Birthday?.ToString("yyyy-MM-dd") ?? "No birthday" )</div>
                          <div class="col-md-16">Pets: @item.Pets?.Count()</div>
                          <div class="col-md-16">Quotes: @item.Quotes?.Count()</div>
                        </div>
                        <div class="col-md-2 themed-grid-col">
                            <a href="~/Details/ViewFriend?id=@item.FriendId" class="btn btn-primary btn-sm" type="button">View</a>
                            <a href="~/Details/EditFriend?id=@item.FriendId"  class="btn btn-secondary btn-sm" type="button">Edit</a>
                            <!-- Button to trigger modal confirmation with modal in the form tag -->
                            <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#delModal"
                                    data-seido-modal-body="@item.FirstName @item.LastName is about to be deleted."
                                    data-seido-selected-item-id="@item.FriendId">
                                Del
                            </button>
                        </div>
                    }
                
                    <nav aria-label="Standard pagination example">
                        <ul class="pagination">
                            <li class="page-item">
                                <a class="page-link" href="~/Overview/ListOfFriends?pagenr=@Model.PrevPageNr&search=@Model.SearchFilter" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            @for (int i = 0; i < Model.NrVisiblePages; i++)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="~/Overview/ListOfFriends?pagenr=@i&search=@Model.SearchFilter">@(i + 1)</a>
                                </li>

                            }
                            <li class="page-item">
                                <a class="page-link" href="~/Overview/ListOfFriends?pagenr=@Model.NextPageNr&search=@Model.SearchFilter" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                }
                <!-- Modal in the form tag -->
                <div class="modal fade" id="delModal" tabindex="-1" aria-labelledby="softModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="softModalLabel">Confirm deletion</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Hello from modal
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <button asp-controller="Overview" asp-action="DeleteFriend" class="btn btn-primary btn-danger">Ok</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>
</div>

AppGoodFriendsMvc/Views/Overview/OverviewCities.cshtml
@model OverviewCitiesModel
@{
    ViewData["Title"] = "Overview City";
}
      
 <!-- Page friends-in-a-country -->
      <div class="container px-4 py-4" id="friends-in-a-country">
        <h2 class="pb-2 border-bottom">Friends in @Model.Country</h2>
        <p>Click in on a city below to see my friends living in that city.</p>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-4 py-5">

          @foreach(var item in Model.FriendPetSummaries)
          {
              if(item.City != null)
              {
                  <div class="col d-flex align-items-start">
                    <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#backpack"/></svg>
                    <div>
                      <h3 class="fw-bold mb-0 fs-4 text-body-emphasis">@item.City</h3>
                      <p>@item.NrFriends friends and @item.NrPets pets.</p>
                      <a href="~/Overview/ListOfFriends?search=@item.City" class="btn btn-primary">
                        See friends
                      </a>    
                    </div>
                  </div>
              }
          }


        </div>
      </div>

AppGoodFriendsMvc/Views/Overview/OverviewCountry.cshtml
@model OverviewCountryModel
@{
    ViewData["Title"] = "Overview Country";
}

<!-- Page friends-by-country -->
      
<div class="container px-4 py-4" id="friends-by-country">
  <h2 class="pb-2 border-bottom">Friends by country</h2>
  <p>Click in on a country below to see what cities my friends are living in.</p>

  <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
    @if (Model.GroupedFriends is not null)
    {
        @foreach (var item in Model.GroupedFriends)
        {
          if(item.Country is not null)
          {
              <a href="~/Overview/OverViewCities?country=@item.Country" class="text-decoration-none">
                <div class="col">
                  <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('./img/unsplash-photo-3.jpg');">
                    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
                      <h3 class="pt-1 mt-1 mb-4 display-6 lh-1 fw-bold">@item.Country</h3>
                        <p class="fs-5"> @item.NrFriends Friends 
                          @if(@item.NrCities != 0) 
                          {
                            <span> in @item.NrCities cities </span>
                          }
                        </p>
                    </div>
                  </div>
                </div>
              </a>
          }
        }
    }
  </div>
</div>