AppGoodFriendsRazor/Pages/EditFriend.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using AppMusicRazor.SeidoHelpers;
using Models;
using Newtonsoft.Json;
using Services;
using Models.DTO;

namespace AppMusicRazor.Pages
{
    public class EditFriendModel : PageModel
    {
        //Web api service
        readonly IFriendsService _service = null;
        readonly ILogger<EditFriendModel> _logger = null;

        [BindProperty]
        public FriendIM FriendInput { get; set; }

        [BindProperty]
        public string PageHeader { get; set; }

        

        //For Validation
        public ModelValidationResult ValidationResult { get; set; } = new ModelValidationResult(false, null, null);

        #region HTTP Requests
        public async Task<IActionResult> OnGet()
        {
            if (Guid.TryParse(Request.Query["id"], out Guid _groupId))
            {
                //Read a music group from 
                var mg = await _service.ReadFriendAsync(_groupId, false);

                //Populate the InputModel from the music group
                FriendInput = new FriendIM(mg);
                PageHeader = "Edit details of a friend";

            }
            else
            {
                //Create an empty music group
                FriendInput = new FriendIM();
                FriendInput.StatusIM = StatusIM.Inserted;
                FriendInput.FirstName = null;
                FriendInput.LastName = null;
                FriendInput.Email = null;
                FriendInput.Birthday = null;
                FriendInput.Address = new AddressIM();
                FriendInput.Address.StatusIM = StatusIM.Inserted;

                PageHeader = "Create a new a friend";
            }

            return Page();
        }

        public async Task<IActionResult> OnPostUndo()
        {
            //Reload Music group from Database
            var mg = await _service.ReadFriendAsync(FriendInput.FriendId, false);

            //Repopulate the InputModel
            FriendInput = new FriendIM(mg);
            return Page();
        }

        public async Task<IActionResult> OnPostSave()
        {
            string[] keys = { "FriendInput.FirstName",
                              "FriendInput.LastName",
                              "FriendInput.Address.ZipCode",
                              "FriendInput.Address.StreetAddress",
                              "FriendInput.Address.City",
                              "FriendInput.Address.Country",};

            if (!ModelState.IsValidPartially(out ModelValidationResult validationResult, keys))
            {
                ValidationResult = validationResult;
                return Page();
            }

            //This is where the music plays
            //First, are we creating a new Music group or editing another
            if (FriendInput.StatusIM == StatusIM.Inserted)
            {
                var newMg = await _service.CreateFriendAsync(FriendInput.CreateCUdto());
                //get the newly created FriendId
                FriendInput.FriendId = newMg.FriendId;
            }

            // Do update address
            var mg = await SaveAddress();

            // Update the Friend itself
            mg = FriendInput.UpdateModel(mg);
            await _service.UpdateFriendAsync(new FriendCUdto(mg));

            if (FriendInput.StatusIM == StatusIM.Inserted)
            {
                return Redirect($"~/ListOfFriends");
            }

            return Redirect($"~/ViewFriend?id={FriendInput.FriendId}");
        }
        #endregion

        #region InputModel Address  saved to database
        private async Task<IFriend> SaveAddress()
        {

            //fetching friend and address from db
            var mg = await _service.ReadFriendAsync(FriendInput.FriendId, false);
            var model = mg.Address;

            //modified address
            var modifiedAddress = FriendInput.Address;
            
            

            //updating or creating address in db
            if(modifiedAddress.StatusIM == StatusIM.Inserted || modifiedAddress.AddressId == default)
            {
                var cuDto = modifiedAddress.CreateCUdto();
                cuDto.FriendsId = new List<Guid>();
                cuDto.FriendsId.Add(mg.FriendId);
                model = await _service.UpsertAddressAsync(cuDto);
            }
            else 
            {
                //updating model from modified
                model = modifiedAddress.UpdateModel(model);
                await _service.UpdateAddressAsync(new AddressCUdto(model));
            }

            mg.Address = model;
            return mg;
        }
        #endregion

        #region Constructors
        public EditFriendModel(IFriendsService service, ILogger<EditFriendModel> logger)
        {
            _service = service;
            _logger = logger;
        }
        #endregion

        #region Input Model 
        public enum StatusIM { Unknown, Unchanged, Inserted, Modified, Deleted}
       
        public class AddressIM
        {
            public StatusIM StatusIM { get; set; }

            public Guid AddressId { get; set; }

            [Required(ErrorMessage = "You must enter a street address")]
            public virtual string StreetAddress { get; set; }

            [Required(ErrorMessage = "You must enter a zip code")]
            public virtual int ZipCode { get; set; }

            [Required(ErrorMessage = "You must enter a city")]
            public virtual string City { get; set; }

            [Required(ErrorMessage = "You must enter a country")]
            public virtual string Country { get; set; }

            public AddressIM() { }
            public AddressIM(AddressIM original)
            {
                StatusIM = original.StatusIM;
                AddressId = original.AddressId;
                StreetAddress = original.StreetAddress;
                ZipCode = original.ZipCode;
                City = original.City;
                Country = original.Country;
            }
            public AddressIM(IAddress model)
            {
                StatusIM = StatusIM.Unchanged;
                AddressId = model.AddressId;
                StreetAddress = model.StreetAddress;
                ZipCode =  model.ZipCode;
                City =  model.City;
                Country =  model.Country;
            }
            
            //to update the model in database
            public IAddress UpdateModel(IAddress model)
            {
                model.AddressId = this.AddressId;
                model.StreetAddress = this.StreetAddress;
                model.ZipCode = this.ZipCode;
                model.City = this.City;
                model.Country = this.Country;
                return model;
            }

            //to create new album in the database
            public AddressCUdto CreateCUdto () => new AddressCUdto(){

                AddressId = null,
                StreetAddress = this.StreetAddress,
                ZipCode = this.ZipCode,
                City = this.City,
                Country = this.Country,
            };
        }
        public class FriendIM
        {
            public StatusIM StatusIM { get; set; }

            public Guid FriendId { get; set; }

            [Required(ErrorMessage = "You must provide a first name")]
            public string FirstName { get; set; }

            [Required(ErrorMessage = "You must provide a last name")]
            public string LastName { get; set; }

            public string Email { get; set; }

            public DateTime? Birthday { get; set; }

            public AddressIM Address { get; set; }

            public FriendIM() {}
            public FriendIM(IFriend model)
            {
                StatusIM = StatusIM.Unchanged;
                FriendId = model.FriendId;
                FirstName = model.FirstName;
                LastName = model.LastName;
                Email = model.Email;
                Birthday = model.Birthday;

                if(model.Address != null)
                {
                    Address = new AddressIM(model.Address);
                }
                

            }

            //to update the model in database
            public IFriend UpdateModel(IFriend model)
            {
                model.FirstName = this.FirstName;
                model.LastName = this.LastName;
                model.Email = this.Email;
                model.Birthday = this.Birthday;
                return model;
            }

            //to create new music group in the database
            public FriendCUdto CreateCUdto () => new (){
                
                FriendId = null,
                FirstName = this.FirstName,
                LastName = this.LastName,
                Email = this.Email,
                Birthday = this.Birthday,
            };

              
        }
        #endregion
    }
}

AppGoodFriendsRazor/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppGoodFriendsRazor.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

AppGoodFriendsRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppGoodFriendsRazor.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

AppGoodFriendsRazor/Pages/ListOfFriends.cshtml.cs
using DbRepos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Models.DTO;
using Services;

namespace AppGoodFriendsRazor.Pages;

public class ListOfFriendsModel : PageModel
{

    private readonly ILogger<ListOfFriendsModel> _logger;
    private GstUsrInfoAllDto _info;
    private  IFriendsService _service;
    public List<IFriend> Friends { get; set; }

    [BindProperty]
    public bool UseSeeds { get; set; } = true;

    public int NrOfFriends { get; set; }

    //Pagination
    public int NrOfPages { get; set; }
    public int PageSize { get; } = 10;

    public int ThisPageNr { get; set; } = 0;
    public int PrevPageNr { get; set; } = 0;
    public int NextPageNr { get; set; } = 0;
    public int NrVisiblePages { get; set; } = 0;

    //ModelBinding for the form
    [BindProperty]
    public string SearchFilter { get; set; } = null;


    public ListOfFriendsModel(ILogger<ListOfFriendsModel> logger, IFriendsService service)
    {
        _logger = logger;
        _service = service;
    }

    public async Task<IActionResult> OnGet()
    {
        //Read a QueryParameters
        if (int.TryParse(Request.Query["pagenr"], out int pagenr))
        {
            ThisPageNr = pagenr;
        }

        SearchFilter = Request.Query["search"];

        //Use the Service
        var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
        Friends = resp.PageItems;
        NrOfFriends = resp.DbItemsCount;

        //Pagination
        UpdatePagination(resp.DbItemsCount);
        

        return Page();
    }
    public async Task<IActionResult> OnPostSearch()
    {
        //Use the Service
        var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
        Friends = resp.PageItems;
        NrOfFriends = resp.DbItemsCount;

        //Pagination
        UpdatePagination(resp.DbItemsCount);

        //Page is rendered as the postback is part of the form tag
        return Page();
    }
    public async Task<IActionResult> OnPostDeleteFriend(Guid friendId)
    {
        await _service.DeleteFriendAsync(friendId);

        //Use the Service
        var resp = await _service.ReadFriendsAsync(UseSeeds, false, SearchFilter, ThisPageNr, PageSize);
        Friends = resp.PageItems;
        NrOfFriends = resp.DbItemsCount;

        //Pagination
        UpdatePagination(resp.DbItemsCount);

        return Page();
    }

    private void UpdatePagination(int nrOfItems)
    {
        //Pagination
        NrOfPages = (int)Math.Ceiling((double)nrOfItems / PageSize);
        PrevPageNr = Math.Max(0, ThisPageNr - 1);
        NextPageNr = Math.Min(NrOfPages - 1, ThisPageNr + 1);
        NrVisiblePages = Math.Min(10, NrOfPages);
    }
}

AppGoodFriendsRazor/Pages/OverviewCountry.cshtml.cs
using DbRepos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models.DTO;
using Services;

namespace AppGoodFriendsRazor.Pages;

public class OverviewCountryModel : PageModel
{

    public List<GstUsrInfoFriendsDto> Friends;
    public List<GroupedFriendsDTO> GroupedFriends;
    public List<GroupedFriendsDTO> UnknownFriends;
    private readonly ILogger<OverviewCountryModel> _logger;
    private GstUsrInfoAllDto _info;
    readonly  IFriendsService _service;

    public OverviewCountryModel(ILogger<OverviewCountryModel> logger, IFriendsService service)
    {
        _logger = logger;
        _service = service;
    }

    public async Task<IActionResult> OnGet()
    {
        //get db info overview
        _info = await _service.InfoAsync();

        //get GstUsrInfoFriendsDto
        Friends = _info.Friends;

        //grouping by country turning GstUsrInfoFriendsDto into GroupedFriendsDTO
        GroupedFriends = Friends.GroupBy(f => f.Country)
                                .Select(c => new GroupedFriendsDTO
                                {
                                    Country = c.Key,
                                    NrFriends = c.Where(f => f.City == null).Sum(f => f.NrFriends),
                                    NrCities = c.Where(f => f.City != null).Select(f => f.City)
                                                .Count() // counting number of cities in the country not including null values
                                })
                                .ToList();

        return Page();
    }
}

AppGoodFriendsRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppGoodFriendsRazor.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

AppGoodFriendsRazor/Pages/ViewFriend.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using Models.DTO;
using Services;

namespace AppMusicRazor.Pages
{
    public class ModalData
    {
        public string postdata { get; set; } 
    }
	public class ViewFriendModel : PageModel
    {
        //Just like for WebApi
        readonly IFriendsService _service = null;
        readonly ILogger<ViewFriendModel> _logger = null;

        public IFriend Friend  { get; set; }

        [BindProperty]
        public Guid FriendId { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Guid _friendId = Guid.Parse(Request.Query["id"]);
            Friend = await _service.ReadFriendAsync(_friendId, false);
            FriendId = _friendId;

            return Page();
        }
        public async Task<IActionResult> OnPostDeletePet(Guid itemId)
        {
            await _service.DeletePetAsync(itemId);
            Friend = await _service.ReadFriendAsync(FriendId, false);

            return Page();
        }
        public async Task<IActionResult> OnPostDeleteQuote(Guid itemId)
        {
            Friend = await _service.ReadFriendAsync(FriendId, false);
            Friend.Quotes = Friend.Quotes.Where(x => x.QuoteId != itemId).ToList();
            await _service.UpdateFriendAsync(new FriendCUdto(Friend));
            Friend = await _service.ReadFriendAsync(FriendId, false);

            return Page();
        }

        //Inject services just like in WebApi
        public ViewFriendModel(IFriendsService service, ILogger<ViewFriendModel> logger)
        {
            _service = service;
            _logger = logger;
        }
    }
}

AppGoodFriendsRazor/Pages/EditFriend.cshtml
@page
@model AppMusicRazor.Pages.EditFriendModel
@using Microsoft.AspNetCore.Authorization;
@{
    ViewData["Title"] = "Edit friend";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@attribute [IgnoreAntiforgeryToken]

<!-- Page add-edit-friend-detail -->
  <div class="container px-4 py-4" id="add-edit-friend">
    <form class="needs-validation" method="post" novalidate>
      <h2 class="pb-2 border-bottom">
            @Model.PageHeader

            <!--Undo button conflicts with client side validation -->
            @* <button class="btn btn-primary-outline" type="button" asp-page-handler="Undo">
                <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#undo" /></svg>
            </button> *@
      </h2>
    <div class="row row-cols-1 row-cols-lg-4 align-items-stretch g-4 py-5">
        <div class="col-md-7 col-lg-8">
          
            <!--To keep between Posts -->
            <input asp-for="PageHeader" value="@Model.PageHeader" type="hidden" />

            <!-- Server side validation errors, rough but just in case client side validation is not working or tampered with -->
            @if (Model.ValidationResult.HasErrors)
            {
                <div class="row g-3">
                    @foreach (var item in Model.ValidationResult.ErrorMsgs)
                    {
                        <span class="alert alert-danger" role="alert">
                            @item
                        </span>
                    }
                </div>
            }


            <div class="row g-3">

                <!-- Hidden fields used to bind input model -->
                <input asp-for="FriendInput.FriendId" type="hidden" />
                <input asp-for="FriendInput.StatusIM" type="hidden" />
                <input asp-for="FriendInput.Address.AddressId" type="hidden" />
                <input asp-for="FriendInput.Address.StatusIM" type="hidden" />
                

              <div class="col-sm-6">
                <label for="firstName" class="form-label">First name</label>
                <input type="text" class="form-control" id="firstName" asp-for="FriendInput.FirstName" value="@Model.FriendInput.FirstName">
                <span asp-validation-for="FriendInput.FirstName" class="invalid-feedback"></span>
              </div>
  
              <div class="col-sm-6">
                <label for="lastName" class="form-label">Last name</label>
                <input type="text" class="form-control" id="lastName" asp-for="FriendInput.LastName" value="@Model.FriendInput.LastName">
                <span asp-validation-for="FriendInput.LastName" class="invalid-feedback"></span>
              </div>
          
              <div class="col-sm-6">
                <label for="email" class="form-label">Email <span class="text-body-secondary">(Optional)</span></label>
                <input type="email" class="form-control" id="email" asp-for="FriendInput.Email" value="@Model.FriendInput.Email">
                <span asp-validation-for="FriendInput.Email" class="invalid-feedback"></span>
              </div>
              <div class="col-sm-6">
                <label for="birthday" class="form-label">Birthday <span class="text-body-secondary">(Optional)</span></label>
                <input type="date" class="form-control" id="birthday" asp-for="FriendInput.Birthday">
                <span asp-validation-for="FriendInput.Birthday" class="invalid-feedback"></span>
              </div>
              
              
              <div class="row g-3 visible">
                <div class="col-12">
                  <label for="address" class="form-label">Address</label>
                  <input type="text" class="form-control" id="address" asp-for="FriendInput.Address.StreetAddress" value="@Model.FriendInput.Address?.StreetAddress">
                  <span asp-validation-for="FriendInput.Address.StreetAddress" class="invalid-feedback"></span>
                </div>
    
                <div class="col-md-3">
                  <label for="zip" class="form-label">Zip</label>
                  <input type="text" class="form-control" id="zip" asp-for="FriendInput.Address.ZipCode" value="@Model.FriendInput.Address?.ZipCode">
                  <span asp-validation-for="FriendInput.Address.ZipCode" class="invalid-feedback"></span>
                </div>

                <div class="col-md-4">
                  <label for="city" class="form-label">City</label>
                  <input type="text" class="form-control" id="city" asp-for="FriendInput.Address.City" value="@Model.FriendInput.Address?.City">
                  <span asp-validation-for="FriendInput.Address.City" class="invalid-feedback"></span>
                </div>
    
                <div class="col-md-5">
                  <label for="country" class="form-label">Country</label>
                  <input type="text" type="text" class="form-control" id="country" asp-for="FriendInput.Address.Country" value="@Model.FriendInput.Address?.Country">
                  <span asp-validation-for="FriendInput.Address.Country" class="invalid-feedback"></span>
              </div>
            </div>
          </div>

          <button class="w-100 btn btn-primary btn-lg my-4" type="submit" asp-page-handler="Save">Save</button>
          
        </div>
      </div>
    </form>
  </div>

@section script
{
    <!-- -->
    <partial name="_ValidationScriptsPartial" />
}

AppGoodFriendsRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div class="container px-4 py-4" id="home">
    <div class="bg-body-tertiary p-5 rounded">
        <div class="col-sm-8 py-5 mx-auto">
            <h1 class="display-5 fw-normal">Torsten Ek's WebApi Project B Good Friends</h1>
              <p class="fs-5">This project is part of the ASP.NET Web Development course, and shows how to combine ASP.NET MVC, Razorpages, which is C# and .NET backend, 
              with css and javascript from Bootstrap in the frontend.</p>
            
              <p>The Project is a Webapplication that communicates and consume the services of the with the goodfriends WebApi that we build in the .NET Data Access course.</p>
              <p></p>
        </div>
    </div>
</div>

AppGoodFriendsRazor/Pages/ListOfFriends.cshtml
@page
@model ListOfFriendsModel
@using Microsoft.AspNetCore.Authorization;
@using Microsoft.AspNetCore.Identity;

@{
    ViewData["Title"] = "List of friends";

}


      
  <!-- Page list-of-friends -->
  <div class="container px-4 py-4" id="list-of-friends">
  <h2 class="pb-2 border-bottom">List of friends</h2>

    <p>There are @Model.NrOfFriends friends 
        @if(Model.SearchFilter is not null)
        {
          <span>matching the search criteria @Model.SearchFilter</span>
        }
    </p>
    <form method="post" class="needs-validation" method="post" novalidate>
      <label class="form-check-label" for="useSeeds">Use seeded data</label>
      <input asp-for="UseSeeds" class="form-check-input" type="checkbox" id="useSeeds">
            <div class="row mb-2 text-center">
                  <!-- Search filter-->
                  <div class="row mb-2 text-center">
                      <div class="col-md-6 ">
                          <input asp-for="SearchFilter" class="form-control" type="search" placeholder="Search" aria-label="Search">
                      </div>
                      <div class="col-md-2 ">
                          <button asp-page-handler="Search" class="btn btn-outline-success" type="submit">Search</button>
                      </div>
                  </div>
            </div>

            <div class="row mb-2 text-center">
              <input type="hidden" name="itemId" data-seido-selected-item-id-target />
              <div class="col-md-4 themed-grid-col">Name</div>
              <div class="col-md-4 themed-grid-col">Address</div>
              <div class="col-md-2 themed-grid-col">Info</div>
              <div class="col-md-2 themed-grid-col">
                  <a href="~/EditFriend" class="btn btn-success btn-sm" type="button">Add</a>
              </div>
            </div>
            <div class="row mb-2 text-center">

                @if(Model.Friends is not null)
                {
                    @foreach(var item in Model.Friends)
                    {
                        <div class="col-md-4 themed-grid-col">
                          @item.FirstName @item.LastName
                          <div class="col-md-16">@item.Email</div>
                        </div>
                        <div class="col-md-4 themed-grid-col">
                          @(item.Address?.StreetAddress ?? "No address" )
                          <div class="col-md-16">@item.Address?.ZipCode @item.Address?.City</div>
                          <div class="col-md-16">@item.Address?.Country</div>
                        </div>
                        <div class="col-md-2 themed-grid-col">
                          <div class="col-md-16">Born: @(item.Birthday?.ToString("yyyy-MM-dd") ?? "No birthday" )</div>
                          <div class="col-md-16">Pets: @item.Pets?.Count()</div>
                          <div class="col-md-16">Quotes: @item.Quotes?.Count()</div>
                        </div>
                        <div class="col-md-2 themed-grid-col">
                            <a href="~/ViewFriend?id=@item.FriendId" class="btn btn-primary btn-sm" type="button">View</a>
                            <a href="~/EditFriend?id=@item.FriendId"  class="btn btn-secondary btn-sm" type="button">Edit</a>
                            <!-- Button to trigger modal confirmation with modal in the form tag -->
                            <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#delModal"
                                    data-seido-modal-body="@item.FirstName @item.LastName is about to be deleted."
                                    data-seido-selected-item-id="@item.FriendId">
                                Del
                            </button>
                        </div>
                    }
                
                    <nav aria-label="Standard pagination example">
                        <ul class="pagination">
                            <li class="page-item">
                                <a class="page-link" href="~/ListOfFriends?pagenr=@Model.PrevPageNr&search=@Model.SearchFilter" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            @for (int i = 0; i < Model.NrVisiblePages; i++)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="~/ListOfFriends?pagenr=@i&search=@Model.SearchFilter">@(i + 1)</a>
                                </li>

                            }
                            <li class="page-item">
                                <a class="page-link" href="~/ListOfFriends?pagenr=@Model.NextPageNr&search=@Model.SearchFilter" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                }
                <!-- Modal in the form tag -->
                <div class="modal fade" id="delModal" tabindex="-1" aria-labelledby="softModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="softModalLabel">Confirm deletion</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Hello from modal
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" asp-page-handler="DeleteFriend" class="btn btn-primary btn-danger">Ok</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>
</div>

AppGoodFriendsRazor/Pages/OverviewCities.cshtml
@page
@model OverviewCitiesModel
@{
    ViewData["Title"] = "Overview City";
}
      
 <!-- Page friends-in-a-country -->
      <div class="container px-4 py-4" id="friends-in-a-country">
        <h2 class="pb-2 border-bottom">Friends in @Model.Country</h2>
        <p>Click in on a city below to see my friends living in that city.</p>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-5 g-4 py-5">

          @foreach(var item in Model.FriendPetSummaries)
          {
              if(item.City != null)
              {
                  <div class="col d-flex align-items-start">
                    <svg class="bi text-body-secondary flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#backpack"/></svg>
                    <div>
                      <h3 class="fw-bold mb-0 fs-4 text-body-emphasis">@item.City</h3>
                      <p>@item.NrFriends friends and @item.NrPets pets.</p>
                      <a href="~/ListOfFriends?search=@item.City" class="btn btn-primary">
                        See friends
                      </a>    
                    </div>
                  </div>
              }
          }


        </div>
      </div>